### ISSUE TITLE
@destroy lifecycle not called on every instance of non-singleton component

### ISSUE THREAD

**Issue by Orp22** [KnisterPeter/tsdi#1204]
Hi,

i found that the @destroy lifecycle is only called on the last instance that was created from a non-singleton scoped component. It's not documented anywhere but i assume the expected behavior would be that it's called on every instance.

I already created a unit test as a repro case but i'm currently not allowed to push branches to this project.

What's the expected behavior and would you accept a PR to fix this?

Cheers,

Tobias

**Comment by KnisterPeter** [comment]
Sorry for th latest reply. That sounds like a bug indeed.
Please create a fork and then you can open a PR.

**Comment by KnisterPeter** [comment]
@Orp22 Tagging you just in case you didn't receive my notice

**Comment by KnisterPeter** [comment]
@Orp22 Still waiting for a PR. Not that you missunderstood me. I would appreciate and integrate your changes if you send me a PR. You don't need to keep a fork and maintain that.

**Comment by Orp22** [comment]
@KnisterPeter Yes, i haven't forgotten about the bug. I just recently moved apartments so i didn't have free time to take care of it. It's not that urgent for me/us as we rarely use non-singleton stores but i will open a PR with a fix as soon as i have it :-)
