### ISSUE TITLE
discussion: decorator-name suggestions

### ISSUE THREAD

**Issue by misantronic** [KnisterPeter/tsdi#141]
For me (or especially others) the keywords `component` or `external` might mean anything or nothing. So, when working with these, I found it useful, to give them more expressives names. For some time now, I am using the following syntax in my project:

`component as injectable`
`external as canInject` in connection with `inject`
`initialize as constructor`

What are your thoughts on this?

**Comment by KnisterPeter** [comment]
My thoughts on this are your names are as meaningless as the current names.
Its just API which is required to learn so feel free to import and rename the decorators. I'm fine with the current names. :smile:
