### ISSUE TITLE
Add docs for `asyncGet`

### ISSUE THREAD

**Issue by raffomania** [KnisterPeter/tsdi#1488]
A doc block for the `asyncGet` method would be awesome. I'm guessing it's related to async constructors, in which case a note in the [section on async dependencies](https://tsdi.js.org/docs/en/next/features#async-dependencies) would also be great.

**Comment by KnisterPeter** [comment]
Hi @raffomania,
that's a good point. Please feel free to provide a PR for this. I'm happy to merge it.

**Comment by raffomania** [comment]
I'm not sure how to write those docs - what is `asyncGet` used for, exactly? I've seen it used in some other projects but couldn't figure out how it works and when it is needed.

**Comment by KnisterPeter** [comment]
Hmm, I thought you where missing it, because you found and and saw it action.
I'll create some docs on it as soon as I find some time to do so.
