### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'configureExternal')

### ISSUE THREAD

**Issue by jguddas** [KnisterPeter/tsdi#1569]
When using `esbuild-loader` I get this error inside `@external`.

[I setup a minimal reproducible example on stackblitz.](https://stackblitz.com/edit/webpack-webpack-js-org-ns6mp8?file=src%2Findex.ts)

**Comment by KnisterPeter** [comment]
Hi @jguddas, `esbuild` does not support typescripts decorator metadata, that means it does not work with decorators at all.

**Comment by KnisterPeter** [comment]
We cannot do anything about, it has to be fixed in esbuild.
