### ISSUE TITLE
Testing mocking doesn't work

### ISSUE THREAD

**Issue by vforv** [KnisterPeter/tsdi#200]
How is possible to mock services, methods, etc?

I tried automock but not working, like this:

```
const tsdi: TSDI = new TSDI();
tsdi.enableAutomock(HemeraInstance);
tsdi.enableComponentScanner();
const main: Main = tsdi.get(Main);

main.startService();
```

But not working it still using old HemeraInstance class

There should be also some way to mock just methods inside class

**Comment by KnisterPeter** [comment]
If you are using jest you could use `jest.fn` for mocking function.
To override (mock) a component you can use `tsdi.override(Class, mockInstance)`. I think its missing in the documentation right now.

This is a simple example:
```js
const tsdi = new TSDI();
tsdi.override(HemeraInstance, {});
tsdi.enableComponentScanner();
const main: Main = tsdi.get(Main);

main.startService();
```
HemeraInstance should be `{}` then.

I'll add this part to the documenation. The 'automock' was an idea but it does not work very well.

**Comment by vforv** [comment]
Hi @KnisterPeter, thanks for answer.

I tried override already but not working as expected.

I did it linke this:

```
const tsdi = new TSDI();
tsdi.override(HemeraInstance, new HemeraInstanceMock);
tsdi.enableComponentScanner();
const main: Main = tsdi.get(Main);

main.startService();
```

**Comment by KnisterPeter** [comment]
@vforv I'm glad to help.

Try to change the order:

```js
const tsdi = new TSDI();
// this registers all components
tsdi.enableComponentScanner();
// this overrides registered components
tsdi.override(HemeraInstance, new HemeraInstanceMock);
const main: Main = tsdi.get(Main);

main.startService();
```
It should work like this.

**Comment by KnisterPeter** [comment]
I'll close this for now since there was no response.
Feel free to comment here or reopen.
