### ISSUE TITLE
Enable `esModuleInterop` in TS config for better Parcel compatibility

### ISSUE THREAD

**Issue by clebert** [KnisterPeter/tsdi#312]
Currently it is not possible to use`tsdi` with Parcel. The "wrong" import of `debug` causes a runtime error. 

Please enable the tsconfig setting `"esModuleInterop": true` and change all imports of `debug` from `import * as debug from 'debug'` to `import debug from 'debug'`.

**Comment by KnisterPeter** [comment]
Released in [v1.0.0-alpha.1](https://github.com/KnisterPeter/tsdi/releases/tag/v1.0.0-alpha.1)
